### ISSUE TITLE
Write Evaluation for Stateless Container Migrations Experiment

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/Relay#14]
* Hypothesis - What was the purpose of the experiment at the beginning
* Conclusion - What did you learn at the end?
* Describe overall architecture - "hub and spoke" model and the usage of bridges and network namespaces
* What Challenges Did you Encounter (any weird or interesting/surprising things?)

You can put this as part of the README.md.

This will help our R&D application for 2018 - 2019 and help other team members understand it.

**Comment by ramwan** [comment]
Done at https://github.com/MatrixAI/Relay/blob/master/experiments/stateless_container_ping_migrations/README.txt
