### ISSUE TITLE
Experiment #2

### ISSUE THREAD

**Issue by ramwan** [MatrixAI/Relay#19]
Found [here](https://github.com/MatrixAI/Relay/tree/master/experiments/automaton_composition_and_networking).

On automaton networking and composition and testing ideas and implementations.

**Comment by ramwan** [comment]
Reworking the experiment structure in order to better model what's going on after a discussion on domain modelling with @CMCDragonkai . Old structure was highly coupled, making it difficult for extensions to be added later and working with and manipulating the data structures were difficult. Here's a sketchup of my thoughts so far on the new structure.

__Composition__ = { Automatons, AbstractInstances }
__Automatons__ = { data related to automaton generation such as maximum number of automatons to be generated of this type, name etc. }
__AbstractInstance__ = { dependency flows, composition flows, ConcreteInstance, other data related to functionality of the automaton in respect to the Relay network }
__ConcreteInstance__ = { network namespace, veth endpoints, IP address of the namespace, other data related to the functionality of the automaton in respect to the kernel }

__FlowTable__ = hashmap of (flowID, dest ip) pairs as (k, v) pairs. This will need to be mutable or at least potentially frequently updatable (State monad?) as automatons may fail for whatever reason.

__NetworkGraph__ = I'm thinking that this could be a multi-layered graph. I haven't enumerated all possible layers but the initial 2 layers would be for dependency and composition flows. The graph could also then have layers for various metrics such as latency on links between nodes. In this way when performing swap overs due to automaton failure, we would do a query on the graph rather than looking up the desired automaton and then picking an instance of that automaton. 

I'm slightly unsure about this structure so any input would be good while I continue to iron out folds.

**Comment by CMCDragonkai** [comment]
I need to dig up some notes about the libp2p swarm graph to see what lessons can be learned there.

**Comment by CMCDragonkai** [comment]
Do you have algebraic constructors for each kind of composition?

**Comment by CMCDragonkai** [comment]
I recommend looking into the monad + interpreter pattern to interpret the composition graph, interpretation should perform libmnl or syscall ops within a resource monad that cleans up after itself once the subgraph is removed.

**Comment by ramwan** [comment]
Update as it's been a while since this experiment was started and the current stage and direction has shifted compared to the initial goal.

The original aim of the experiment was to translate automaton compositions into a concrete network instantiated into the kernel. To do this we came up with compositions such as `->` representing a one way communication from left to right and `<-`, the opposite. This however turned out to be an inadequate description of what's actually going on in the network as we can split a communication stream into its constituent layers (eg. HTTP on TCP on IP).
For this experiment I then just picked arbitrarily to work at the IP level by dealing with the instantiation of network namespaces and veth pairs. This way, I only had to deal with which automatons needed to be connected to who without having to manage the communication flow between automatons.

At this point, it's become clear to me that we are able to translate an initial graph of automatons into a graph which can then be instantiated into the kernel (although I haven't implemented it yet). The experiment is close to reaching this stage right now - I need to use haskell's FFI.

However after more discussion with @CMCDragonkai, we've realised that the graph transformations in this experiment are very rudimentary and are only a starting point in order to test the waters in terms of implementation details and ideas.
One point raised is the need for the transformation process to be able to be reactive to the end network state, much like how the browser's DOM is reactive to elements being changed. This hasn't been taken into account in the experiment currently.
We've also not taken into account the need for this Orchestrator-like program to run across many different nodes across a network which will no doubt throw a wrench in the workings.

As a result, I think that the experiment probably could be pushed forward to conclude with simple automaton compositions which can be instantiated by the haskell program in order to be able to move on.

**Comment by CMCDragonkai** [comment]
Distributed graphs will either have to be replicated or sharded. Replication is really intended to improve availability (via redundancy and latency reduction). But replication is ultimately wasteful, whereas sharding can improve performance. In fact I have a feeling that this difference is actually captured by the idea of normalisation vs denormalisation in RDBMSes. Anyway we'll address this problem later.

**Comment by CMCDragonkai** [comment]
As a starting point for Haskell's FFI interpretation, I recommend to look at some VPN implementations to get some ideas, I have a feeling that having lots of veth pairs might not be the most performant.

**Comment by CMCDragonkai** [comment]
https://www.wireguard.com/performance/

**Comment by ramwan** [comment]
Graph transformation research hit a wall for now and no progress has been made. Further experiments were done to further the idea of abstract addresses to enable connection migration though.
