### ISSUE TITLE
Container networking tests

### ISSUE THREAD

**Issue by ramwan** [MatrixAI/Relay#7]
This is an issue to track the networking of containers and the difficulty/effects of various implementations. These experiments are intended to only work on Linux systems and with Docker containers initially.

## Linux networking technologies
- VxLan
- tuntap
- Veth
- Bridges
- Iptables
- Macvlan
- Vlan
- IPVS

## Current networking solutions
- Koko
- Weavenet
- Cilium

**Comment by ramwan** [comment]
@olligobber  yes it is thank you!

**Comment by CMCDragonkai** [comment]
https://github.com/MatrixAI/container-practices/tree/master/network-experiments has macvlan, vlan and namespace test.

**Comment by ramwan** [comment]
First experiments on implementing service abstractions and stateless container migrations, found [here](https://github.com/MatrixAI/Relay/tree/master/experiments/stateless_container_ping_migrations)

**Comment by ramwan** [comment]
closed as experiments are being tracked in issues relevant to specific topics and to the directory found at
[https://github.com/MatrixAI/Relay/tree/master/experiments](https://github.com/MatrixAI/Relay/tree/master/experiments)
