### ISSUE TITLE
Examination of Serval

### ISSUE THREAD

**Issue by ramwan** [MatrixAI/Relay#9]
Review of Serval's architecture and whether it may be applicable to Matrix.
https://github.com/MatrixAI/Relay/tree/master/research/Serval
https://www.cs.princeton.edu/~jrex/papers/serval-nsdi12.pdf
https://github.com/MatrixAI/Relay/tree/master/papers/Serval
https://github.com/princeton-sns/serval

## Running summary of the paper for TLDR
Serval's architecture proposes a slightly alternate networking stack compared to the TCP/IP stack with the introduction of a service layer. The changes split a name into:

    service name - who we communicate with
    flow name - what communication context to use
    addresses - where to direct communication

A summary of the differences in layering compared to the TCP/IP stack can be seen as follows.

  (network layer)     | src addr | dest addr | ...
  (service layer)     | source flowID | dest flowID | trans prot | serviceID |
  (transport layer)   | app prot | ....

as compared to

  (network layer)    | src addr | dest addr | ...
  (transport layer)  | src port | dest port | ...

Serval also proposes service discovery by forwarding packets addressed to a serviceID and leaving the network address of the service provider to be determined by routers closer to actual services with more detailed information on load of servers.

**Comment by CMCDragonkai** [comment]
Serval implements their new features as new syscalls.

I don't think that's a good direction to pursue as we discussed before the problems with doing that.

However the underlying core functionality may still be useful. So having a read of that, while not doubling down on the exact implementation is a good idea.

**Comment by ramwan** [comment]
Serval's architecture proposes a slightly alternate networking stack compared to the TCP/IP stack with the introduction of a service layer. The changes split a name into:
- service name - *who* we communicate with
- flow name - *what* communication context to use
- addresses - *where* to direct communication

A summary of the differences in layering compared to the TCP/IP stack can be seen as follows.
```
  (network layer)     | src addr | dest addr | ...
  (service layer)     | source flowID | dest flowID | trans prot | serviceID |
  (transport layer)   | app prot | ....
```

as compared to
```
  (network layer)    | src addr | dest addr | ...
  (transport layer)  | src port | dest port | ...
```
Serval also proposes service discovery by forwarding packets addressed to a serviceID and leaving the network address of the service provider to be determined by routers closer to actual services with more detailed information on load of servers.

The Serval proposition also suggests to have an interface very similar to the BSD sockets interface by calling
```
socket s = bind(serviceID)
```
which would create a socket which maps to at least 1 FlowID.
This is an interesting concept which relates to Matrix because the paper describes in section 4.4 how ```socket s``` can actually map to multiple FlowIDs (Figure 6 in the paper).

Drawing from how a single socket can have multiple FlowIDs which each can indicate a different interface, this means that an application doesn't have to be aware of the changing of a network address as long as the FlowIDs remain the same, meaning that both ends of a communication channel can migrate to a different interface (read: different physical machine) and communication, from a very high level, would not have been disrupted at all.

However, I'm not quite sure how an implementation would go. Will need to examine Serval's sample implementations and see whether we can do it without creating new syscalls or a user-space networking stack.

**Comment by ramwan** [comment]
I've also thought of some potential issues that may occur when using the proposed Serval implementation.Keeping in mind that all physical hosts in the Matrix network are well known within the network as are serviceIDs as automatons are composed with each other in the language.
```                                                                            
  > A wants to talk to B.                                                       
  > A creates                                                                   
    / SERV_ID / large_random_number / empty_dest_flow /                         
    and forwards this to a random link                                          
  > Intermediate machines (if any) inspect SERV_ID ::                           
      case DEST_SERV_UNKNOWN:                                                   
        foward to a random link                                                 
        *issue: packet travels in circles. Do we need some form of topology knowledge
                   or routing table?                                     
        *issue: are we dealing with malicious nodes? if so is there an issue    
                with nodes just accepting requests on a service ID even if they 
                don't have the service? or does the language specification      
                prevent that                                                    
      case DEST_SERV_KNOWN:                                                     
        forward to correct service                                              
        *issue: randomness may mean some servers are overloaded while others    
                empty. This effect especially may be amplified in networks with 
                imbalanced links eg.                                            
                                                                                
                    B - C                                                       
                  /  \                                                          
                A     D                                                         
                |         where I, G, H, D are destination servers and A issues the request
                |                                                               
            I - E - F                                                           
             \  |\                                                              
              \ | H                                                             
                G                                                               
                                                                                
                How is this a problem? A only has 2 links and without knowledge 
                of the overall topology, each link will have a 50% chance of    
                having a service request forwarded to it. Hence D will get full 
                much faster whereas I, G, H will still have plenty of load to   
                carry.                                                          
        *issue: if multiple automatons discover the same server, do they always 
                send requests to that server? they should probably also randomly
                send requests to other links to attempt to discover other       
                servers
```

**Comment by CMCDragonkai** [comment]
Our discussion on this led us to think:

1. We don't want to create new syscalls in order to maintain compatibility with existing software.
2. The concept of a flow as a layer of indirection between service names and IPs, can be represented in our system, but controlling the names that we pass down to each Automaton. That is the ip that we pass into a service can be just a virtual IP, that maps to a concrete IP later.
3. We should look into source code implementation of serval to better understand how the mapping is done.
4. Then compare that to the kernel network stack or network address translation system to see how it is done.

**Comment by ramwan** [comment]
Another point in our discussion was the transition between points which are stateful vs stateless. For example, let's have a look at a  sample situation where 2 applications are communicating. 
```
INITIAL STATE         
                                                                       
        HOST 1                                         HOST 2                   
                                                                                
      app socket                                      app socket                
  ----|-------------------                    --------|--------------           
      |                                               |                         
  flow1                                          flow3                          
    |                                               |                           
  --|--------------------                     ------|-----------------          
    |                                               |                           
  100.0.0.1                                         +-243.0.0.2                 
    |                                                    |                      
  --|--------------------                     -----------|------------          
    |                                                    |                      
    |                                                    |                      
    +----------------------------------------------------+                      
                                                                                
------------------------------------------------------------------------------- 
TRANSITION STATE                            
                                                    
        HOST 1                                         HOST 2                   
                                                                                
      app socket                                      app socket                
  ----|-------|-----------                    --------|-------|------           
      |       |                                       |       |                 
  flow1       flow2                               flow3       flow4             
    |           |                                   |           |               
  --|-----------|--------                     ------|-----------|-----          
    |           |                                   |           |               
  100.0.0.1    100.0.0.2                            +-243.0.0.2-+               
    |            |                                       |                      
  --|------------|-------                     -----------|------------          
    +------+---- +                                       |                      
           |                                             |                      
           +---------------------------------------------+                      
                                                                                
------------------------------------------------------------------------------- 
END STATE                         
                                                       
        HOST 1                                         HOST 2                   
                                                                                
      app socket                                      app socket                
  ------------|-----------                    ----------------|------           
              |                                               |                 
              flow2                                           flow4             
                |                                               |               
  --------------|--------                     ------------------|-----          
                |                                               |               
               100.0.0.2                              243.0.0.2-+               
                 |                                       |                      
  ---------------|-------                     -----------|------------          
                 |                                       |                      
                 |                                       |                      
                 +---------------------------------------+ 
```
If no state is required to be kept between communications, then whether the application is running on the same physical machine as the new flow doesn't matter as long as the programmer's application still is able to see the same socket. Of course fine details will still need to be ironed out such as exactly how this will work across different physical machines (eg. even though communication may be stateless, the application may itself require state to manage this socket).

However, if communication state is required (eg. tcp flow), potentially we could have state stored in a sort of key-value store linked by flow identifiers. That way, flow1 and flow2 in the above example can 'point' to the same data, much like how pointers to pointers.

**Comment by ramwan** [comment]
After some initial examinations of the [Serval source code](https://github.com/princeton-sns/serval), I think that the Serval socket type is an extension of existing linux socket types. Also by looking at the definition of the Serval socket, I've noticed that it only has
```
struct serval_sock {
...
struct flow_id local_flowid;
struct flow_id peer_flowid;
---
};
```
which I believe means that the implementation only reached the stage where application sockets were only able to have 1 flow assigned to them. Whether this is actually meant to stay as is or the authors abandoned the project before developing that feature I'm not quite sure but I quite like the idea of having multiple flows attached to 1 socket still.

Migrating a flow to a different interface while having it remain on the same socket is basically done by tracking state in the socket struct and sending off a 'RSYN' packet across the new interface with the same flowid and, depending on the response, we can mark the socket as having the flow fully migrated. I think this means that Serval clients have a separate protocol for communication. Not sure whether this protocol is documented (or is this actually a different/modified protocol?)

**Comment by ramwan** [comment]
> The concept of a flow as a layer of indirection between service names and IPs, can be represented in our system, but controlling the names that we pass down to each Automaton. That is the ip that we pass into a service can be just a virtual IP, that maps to a concrete IP later.

I've thought more about that point in particular. noted [here](https://github.com/MatrixAI/Relay/blob/master/design/service_naming/socket_flow_abstraction.txt). I think that the virtual IP idea is a good way to do it. Here's an example from my notes which I think demonstrate the benefits of using a virtual IP as the flow identifier.

```
  - Automaton A wants to talk to any Automaton B                                
  - A resides in a separate network namespace connected to a
    physical interface through any number of virtual interfaces            
  - A has B's service name but not its network address and so asks to have this 
    service name resolved.                                                      
    - A's request goes through virtual interfaces which connect to the physical
      network via a mapping service. Here A's outbound request through whatever
      socket is noted down and an identifier is assigned to it.                                      
  - B's network address arrives back at the physical interface which A resides  
    on. The response travels back through the mapping service which holds the mapping of  
    A's socket, it's identifier and now B's network address.
   A potential mapping could look like the following:

   [A_sock, A_ip, B_ip, B_sock, virtual_mapping]                                                                   

  - The mapping returns to Automaton A the virtual identifier
    and now A is able to send service requests to a B by calling, in C for      
    example, `connect(int socket,                                               
                      struct sockaddr *flow_identifier,                       
                      socklen_t addr_len);`.                                    
```
Here I'm letting the identifer of the connection be either an IPv4 or IPv6 address and B's service name to be a regular url such as https://serviceB.matrix.com/. This way if the containers were to be run without a Matrix network, the developers wouldn't need to change any code - they would just rely on existing DNS infrastructure.

I think that if the services reside in a Matrix network, it shouldn't matter whether the service names presented resolve via DNS or not as services are only communicating with each other within the network. However if the developers were to run the services outside of the Matrix network the names would need to resolve properly.

**Comment by ramwan** [comment]
initial design inspiration taken from Serval seems to work. closing this issue now as further testing later will iron out details of implementation.
